# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tpbrandomizer.fullname" . }}
  labels:
    app: {{ include "tpbrandomizer.name" . }}
spec:
  ports:
    - port: 4000
      targetPort: 4000
  selector:
    app: {{ include "tpbrandomizer.name" . }}
